---
- hosts: all
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: {{ playbook_dir }}/nginx-repo.crt
          key: {{ playbook_dir }}/nginx-repo.key
