---
- hosts: all
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: "/var/lib/awx/venv/ansible/nginx-repo.crt"
          key: "/var/lib/awx/venv/ansible/nginx-repo.key"
